version: '3.7'

services:
    dev:
        container_name: dev
        build:
            context: .
            dockerfile: dev.Dockerfile
        image: dev
        volumes:
            - ./..:/home/ubuntu/AdaptiveBuffers
